name: CI
on:
  - pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: https://npm.pkg.github.com
      - run: yarn install
      - run: yarn lint
      - run: yarn typecheck
